[project]
name = "gsm-controller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dishka>=1.7.2",
    "fastapi[standard]>=0.128.0",
]
